
lucide.createIcons();
var inputText=document.getElementById('inputText');
var charCount=document.getElementById('charCount');
var generateBtn=document.getElementById('generateBtn');
var outputBody=document.getElementById('outputBody');
var copyBtn=document.getElementById('copyBtn');
var regenerateBtn=document.getElementById('regenerateBtn');
var toastEl=document.getElementById('toast');
document.querySelectorAll('.segmented').forEach(function(g){g.querySelectorAll('button').forEach(function(b){b.addEventListener('click',function(){g.querySelectorAll('button').forEach(function(x){x.classList.remove('active')});b.classList.add('active')})})});
inputText.addEventListener('input',function(){charCount.textContent=inputText.value.length});
var toastTimer=null;
function showToast(m){toastEl.textContent=m;toastEl.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(function(){toastEl.classList.remove('show')},2500)}
async function callProxy(prompt){var resp=await fetch('/api/generate-report',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(prompt)});if(!resp.ok){var e=await resp.json();throw new Error(e.error||'璇锋眰澶辫触 ('+resp.status+')')}var d=await resp.json();return (d.choices?.[0]?.message?.content||'')}
function buildPrompt(input,tone,role){var system='浣犳槸涓€涓笓涓氱殑鍛ㄦ姤鍐欎綔鍔╂墜銆傛牴鎹敤鎴锋彁渚涚殑闆舵暎宸ヤ綔璁板綍锛岀敓鎴愪竴浠界粨鏋勬竻鏅般€佽〃杈句笓涓氱殑鍛ㄦ姤銆俓n\n鍛ㄦ姤鍖呭惈浠ヤ笅涓変釜閮ㄥ垎锛歕n1. 鏈懆宸ヤ綔鍐呭 - 灏嗙敤鎴锋彁渚涚殑宸ヤ綔璁板綍鏁寸悊鎴愭湁鏉＄悊鐨勬弿杩帮紝鐢ㄩ」鐩鍙峰垪鍑篭n2. 鍏抽敭鎴愭灉 - 鎻愮偧鏈懆鏈€涓昏鐨勫伐浣滄垚鏋滐紝鐢ㄦ暟鎹垨鍏蜂綋浜嬪疄鏀拺\n3. 涓嬪懆璁″垝 - 鍩轰簬鏈懆宸ヤ綔鎺ㄦ祴鍚堢悊鐨勪笅鍛ㄥ伐浣滆鍒掞紝2-3鏉★紝鐢ㄩ」鐩鍙峰垪鍑篭n\n璇皵椋庢牸锛?+tone+'\n- 姝ｅ紡锛氭爣鍑嗚亴鍦虹敤璇紝鎺緸涓ヨ皑\n- 绠€娲侊細鍙閲嶇偣锛屾瘡閮ㄥ垎2-3鍙ヨ瘽\n- 閭€鍔熺増锛氱獊鍑轰釜浜鸿础鐚拰浠峰€硷紝閫傚綋鍖呰鎴愭灉\n\n瑙掕壊锛?+role+'\n- 鏅€氬憳宸ワ細浠庢墽琛岃€呰瑙掓弿杩癨n- 绠＄悊鑰咃細浠庡洟闃熺鐞嗗拰鍐崇瓥瑙嗚鎻忚堪\n- 鑷敱鑱屼笟鑰咃細浠庨」鐩氦浠樺拰瀹㈡埛瑙嗚鎻忚堪\n\n鐩存帴杈撳嚭鍛ㄦ姤鍐呭锛屼笉瑕佽緭鍑洪澶栬鏄庛€傜敤 markdown 鏍煎紡杈撳嚭锛屼笁閮ㄥ垎鐨勬爣棰樼敤 ###銆?;return{system:system,userInput:input}}
function formatOutput(text){var h='';var lines=text.split('\n');var currentSection=null;var sectionContent=[];function flushSection(){if(currentSection&&sectionContent.length>0){h+='<div class="report-section"><h3>'+currentSection+'</h3>';var j=sectionContent.join('\n');if(/^[-*]\s/m.test(j)){h+='<ul>';sectionContent.forEach(function(l){if(/^[-*]\s/.test(l.trim())){h+='<li>'+l.trim().replace(/^[-*]\s/,'')+'</li>'}else if(l.trim()){h+='<li>'+l.trim()+'</li>'}});h+='</ul>'}else{sectionContent.forEach(function(l){if(l.trim())h+='<p>'+l.trim()+'</p>'})}h+='</div>'}sectionContent=[]}lines.forEach(function(l){if(/^###\s/.test(l.trim())){flushSection();currentSection=l.trim().replace(/^###\s*/,'')}else if(currentSection){sectionContent.push(l)}else{if(l.trim())h+='<p>'+l.trim()+'</p>'}});flushSection();if(!h)h='<div class="report-section"><p>'+text.replace(/\n/g,'<br>')+'</p></div>';return h}
async function generate(){var apiKey='dummy';var input=inputText.value.trim();if(!input){showToast('璇疯緭\u5165杩欏懆鐨勫伐浣滃唴瀹?);inputText.focus();return}var tone=(document.querySelector('#toneGroup .active')?.dataset?.value)||'姝ｅ紡';var role=(document.querySelector('#roleGroup .active')?.dataset?.value)||'鏅€氬憳宸?;generateBtn.disabled=true;generateBtn.innerHTML='<div class="spinner"></div><span>鐢熸垚涓?..</span>';outputBody.innerHTML='<div class="output-empty"><div class="spinner" style="margin:0 auto 12px"></div>姝ｅ湪鐢熸垚鍛ㄦ姤...</div>';copyBtn.style.display='none';regenerateBtn.style.display='none';try{var prompt=buildPrompt(input,tone,role);var result=await callProxy(prompt);outputBody.innerHTML=formatOutput(result);copyBtn.style.display='';regenerateBtn.style.display='';showToast('\u5468鎶ョ敓鎴愬畬鎴?)}catch(err){outputBody.innerHTML='<div class="output-empty"><i data-lucide="alert-circle" width="40" height="40" style="display:block;margin:0 auto 12px;color:#ef4444"></i><div style="color:#991b1b;font-weight:500;margin-bottom:4px">鐢熸垚澶辫触</div><div style="font-size:13px">'+err.message+'</div></div>';lucide.createIcons();showToast('\u751f\u6210\u5931\u8d25: '+err.message)}finally{generateBtn.disabled=false;generateBtn.innerHTML='<i data-lucide="wand-sparkles" width="18" height="18"></i><span>鐢熸垚鍛ㄦ姤</span>';lucide.createIcons()}}
generateBtn.addEventListener('click',generate);
regenerateBtn.addEventListener('click',generate);
copyBtn.addEventListener('click',async function(){var t=(outputBody.textContent||'').trim();if(!t){showToast('娌℃湁鍐呭鍙鍒?);return}try{await navigator.clipboard.writeText(t);var ic=copyBtn.querySelector('i');ic.setAttribute('data-lucide','check');lucide.createIcons();showToast('宸插鍒跺埌鍓创鏉?);setTimeout(function(){ic.setAttribute('data-lucide','clipboard');lucide.createIcons()},1500)}catch(e){showToast('澶嶅埗澶辫触锛岃鎵嬪姩澶嶅埗')}});
document.addEventListener('keydown',function(e){if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();generate()}});
lucide.createIcons();

