
lucide.createIcons();
var inputText=document.getElementById('inputText');
var charCount=document.getElementById('charCount');
var generateBtn=document.getElementById('generateBtn');
var outputBody=document.getElementById('outputBody');
var copyBtn=document.getElementById('copyBtn');
var regenerateBtn=document.getElementById('regenerateBtn');
var toastEl=document.getElementById('toast');
document.querySelectorAll('.segmented').forEach(function(g){g.querySelectorAll('button').forEach(function(b){b.addEventListener('click',function(){g.querySelectorAll('button').forEach(function(x){x.classList.remove('active')});b.classList.add('active')})})});
inputText.addEventListener('input',function(){charCount.textContent=inputText.value.length});
var toastTimer=null;
function showToast(m){toastEl.textContent=m;toastEl.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(function(){toastEl.classList.remove('show')},2500)}
async function callProxy(prompt){var resp=await fetch('/api/generate-report',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(prompt)});if(!resp.ok){var e=await resp.json();throw new Error(e.error||'请求失败 ('+resp.status+')')}var d=await resp.json();return (d.choices?.[0]?.message?.content||'')}
function buildPrompt(input,tone,role){var system='你是一个专业的周报写作助手。根据用户提供的零散工作记录，生成一份结构清晰、表达专业的周报。\n\n周报包含以下三个部分：\n1. 本周工作内容 - 将用户提供的工作记录整理成有条理的描述，用项目符号列出\n2. 关键成果 - 提炼本周最主要的工作成果，用数据或具体事实支撑\n3. 下周计划 - 基于本周工作推测合理的下周工作计划，2-3条，用项目符号列出\n\n语气风格：'+tone+'\n- 正式：标准职场用语，措辞严谨\n- 简洁：只说重点，每部分2-3句话\n- 邀功版：突出个人贡献和价值，适当包装成果\n\n角色：'+role+'\n- 普通员工：从执行者视角描述\n- 管理者：从团队管理和决策视角描述\n- 自由职业者：从项目交付和客户视角描述\n\n直接输出周报内容，不要输出额外说明。用 markdown 格式输出，三部分的标题用 ###。';return{system:system,userInput:input}}
function formatOutput(text){var h='';var lines=text.split('\n');var currentSection=null;var sectionContent=[];function flushSection(){if(currentSection&&sectionContent.length>0){h+='<div class="report-section"><h3>'+currentSection+'</h3>';var j=sectionContent.join('\n');if(/^[-*]\s/m.test(j)){h+='<ul>';sectionContent.forEach(function(l){if(/^[-*]\s/.test(l.trim())){h+='<li>'+l.trim().replace(/^[-*]\s/,'')+'</li>'}else if(l.trim()){h+='<li>'+l.trim()+'</li>'}});h+='</ul>'}else{sectionContent.forEach(function(l){if(l.trim())h+='<p>'+l.trim()+'</p>'})}h+='</div>'}sectionContent=[]}lines.forEach(function(l){if(/^###\s/.test(l.trim())){flushSection();currentSection=l.trim().replace(/^###\s*/,'')}else if(currentSection){sectionContent.push(l)}else{if(l.trim())h+='<p>'+l.trim()+'</p>'}});flushSection();if(!h)h='<div class="report-section"><p>'+text.replace(/\n/g,'<br>')+'</p></div>';return h}
async function generate(){var apiKey='dummy';var input=inputText.value.trim();if(!input){showToast('请输\u5165这周的工作内容');inputText.focus();return}var tone=(document.querySelector('#toneGroup .active')?.dataset?.value)||'正式';var role=(document.querySelector('#roleGroup .active')?.dataset?.value)||'普通员工';generateBtn.disabled=true;generateBtn.innerHTML='<div class="spinner"></div><span>生成中...</span>';outputBody.innerHTML='<div class="output-empty"><div class="spinner" style="margin:0 auto 12px"></div>正在生成周报...</div>';copyBtn.style.display='none';regenerateBtn.style.display='none';try{var prompt=buildPrompt(input,tone,role);var result=await callProxy(prompt);outputBody.innerHTML=formatOutput(result);copyBtn.style.display='';regenerateBtn.style.display='';showToast('\u5468报生成完成')}catch(err){outputBody.innerHTML='<div class="output-empty"><i data-lucide="alert-circle" width="40" height="40" style="display:block;margin:0 auto 12px;color:#ef4444"></i><div style="color:#991b1b;font-weight:500;margin-bottom:4px">生成失败</div><div style="font-size:13px">'+err.message+'</div></div>';lucide.createIcons();showToast('\u751f\u6210\u5931\u8d25: '+err.message)}finally{generateBtn.disabled=false;generateBtn.innerHTML='<i data-lucide="wand-sparkles" width="18" height="18"></i><span>生成周报</span>';lucide.createIcons()}}
generateBtn.addEventListener('click',generate);
regenerateBtn.addEventListener('click',generate);
copyBtn.addEventListener('click',async function(){var t=(outputBody.textContent||'').trim();if(!t){showToast('没有内容可复制');return}try{await navigator.clipboard.writeText(t);var ic=copyBtn.querySelector('i');ic.setAttribute('data-lucide','check');lucide.createIcons();showToast('已复制到剪贴板');setTimeout(function(){ic.setAttribute('data-lucide','clipboard');lucide.createIcons()},1500)}catch(e){showToast('复制失败，请手动复制')}});
document.addEventListener('keydown',function(e){if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();generate()}});
lucide.createIcons();
